server:
  port: 8081
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.102.223.67:8081/mu_qiang_access?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mqa.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: default
logging:
  level:
    com:
      mqa:
        mapper: debug
        service: info
        controller: info
mqa:
  jwt:
    secret-key: mu_qiang_access
    duration: 72000000
    token-name: token

springdoc:
  swagger-ui:
    path: /swagger-ui.html
